import type { NextPage } from 'next'
import Head from 'next/head'

import RegistrationForm from '../components/organisms/RegistrationForm';
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <RegistrationForm/>
        <div></div>
      </main>
    </div>
  )
}

export default Home
